## Concatenating vs Stacking Tensor

With different python libraries:

1. Pytorch
2. Tensorflow
3. Numpy

A. Contacting joins a sequence of tensor along existing axis.

B. Stacking joins as sequence of tensor along new axis.

### 1. Pytotch

In [18]:
import torch

In [19]:
t1=torch.tensor([1,1,1])
t2=torch.tensor([2,2,2])
t3=torch.tensor([3,3,3])


In [20]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [21]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [22]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [23]:
torch.cat(
    (t1,t2,t3),
    dim=0
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

* Notice no new axis is created and all elements are added to same axis

In [24]:
torch.stack(
    (t1,t2,t3),
    dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

* Notice we have a new axis now for rows.
* similar result can be obatined by adding a extra axis to tensor and concaneting them 

In [25]:
torch.cat(
    (
        t1.unsqueeze(0),
        t2.unsqueeze(0),
        t3.unsqueeze(0),
    ),
    dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

* Although we obtained same result the code of stacking was much cleaner than cat.

* Let us try to concate them along second axis

* This will fail becuase we do not have any second axis, so stacking is our only choice


In [26]:
torch.stack(
    (t1,t2,t3),
    dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

* This is similar to us inserting a new axis at dim=1
* To cat them we use following code: notice that dim=1

In [27]:
torch.cat(
    (
        t1.unsqueeze(1),
        t2.unsqueeze(1),
        t3.unsqueeze(1),
    ),
    dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

##### Examples:

1. We have 10 images with Height x Width x Channels
    * We need to create a tensor with batch this images
    * The batch should be of type: Batch x Height x Width x Channels

Ans 1. Stack is our only choice because image has 3 dimensions while batch needs 4 dimesnions

2. We have 10 images with Batch x Height x Width x Channels
    * We need to create a tensor with batch this images
    * The batch should be of type:  Batch x Height x Width x Channels

Ans 2. Since we already have a batch dimesnion, we do not need to stack this this images, all we have to do jus conact along the batch axis

3. We have 10 images with Height x Width x Channels and Existing tensor with group of images and dimesnion of Batch x Height x Width x Channels.

Ans 3. Neither of this will work as one has 4 dimensions and other has 3 dimensions.
Procedure: Stack the 10 images and then concate them with batch tensor

### 2. Tensorflow

In [28]:
import tensorflow as tf

In [29]:
t1=tf.constant([1,1,1])
t2=tf.constant([2,2,2])
t3=tf.constant([3,3,3])

In [30]:
tf.concat(
    (t1,t2,t3),
    axis=0
)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int32)>

In [31]:
tf.stack(
    (t1,t2,t3),
    axis=0
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

* Diffrene:
    1. cat vs concat
    2. dim vs axis
    3. unsqueeze vs expand_dims

In [32]:
tf.concat(
    (
    tf.expand_dims(t1,0),
    tf.expand_dims(t2,0),
    tf.expand_dims(t3,0),
    ),
    axis=0
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

### 3. Numpy 

In [33]:
import numpy as np

In [34]:
t1=np.array([1,1,1])
t2=np.array([2,2,2])
t3=np.array([3,3,3])


In [35]:
np.concatenate(
    (t1,t2,t3),
    axis=0
)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [36]:
np.stack(
    (t1,t2,t3),
    axis=0
)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

* Diffrene:
    1. cat vs concat vs concatenate
    2. dim vs axis vs axis
    3. unsqueeze vs expand_dims vs expand_dims

In [40]:
np.concatenate(
    (
    np.expand_dims(t1,0),
    np.expand_dims(t2,0),
    np.expand_dims(t3,0),
    ),
    axis=0
)

AttributeError: module 'numpy' has no attribute 'concatenatecate'